export const QUESTIONS = [
  {
    id: 'city',
    type: 'city',
    text: 'What city are you in?',
  },
  {
    id: 'attendance',
    type: 'choice',
    text: 'Will you be celebrating with us in person in NYC, or joining the fun from afar?',
    options: ['In person', 'Remote'],
  },
  {
    id: 'favourite-fruit',
    type: 'text',
    emoji: '🍊',
    text: "Before Wanda discovered and fell in love with grapefruits at the tender age of 16, what was her favourite fruit?",
    hint: 'Hint: it was NOT on the quiz last year',
  },
  {
    id: 'if-you-were-a-wine',
    type: 'text',
    emoji: '🍾',
    text: 'If you were a wine, what would you be and why?',
  },
  {
    id: 'rank-glasses',
    type: 'rank',
    emoji: '🍷',
    text: "Rank these wine glasses from Wanda's most to least preferred vessel for drinking wine",
    hint: 'Drag to reorder — #1 is most preferred',
    options: [
      { id: 'angular-stem',     label: 'Angular Goblet with Tall Skinny Stem',   image: '/glasses/angular-stem.jpg' },
      { id: 'rounded-stem',     label: 'Rounded Goblet with Tall Skinny Stem',    image: '/glasses/rounded-stem.jpg' },
      { id: 'stemless',         label: 'Stemless Wine Glass',                      image: '/glasses/stemless.jpg' },
      { id: 'wine-cooler-mug',  label: 'Wine Cooler Mug',                          image: '/glasses/wine-cooler-mug.jpg' },
      { id: 'mug',              label: 'A Mug',                                    image: '/glasses/mug.jpg' },
      { id: 'short-thick-stem', label: 'Short Wine Glass with Thick Stem',         image: '/glasses/short-thick-stem.jpg' },
    ],
  },
  {
    id: 'rank-wines',
    type: 'rank',
    emoji: '🍷',
    text: "Rank Wanda's Fave Wines",
    hint: 'Drag to reorder — #1 is most favourite',
    options: [
      { id: 'rose',          label: 'Rosé' },
      { id: 'riesling',      label: 'Riesling' },
      { id: 'pinot-grigio',  label: 'Pinot Grigio' },
      { id: 'chilled-malbec',label: 'Chilled Malbec' },
      { id: 'pinot-noir',    label: 'Pinot Noir' },
    ],
  },
  {
    id: 'grape-debate',
    type: 'text',
    emoji: '🍇',
    text: "Let's settle the great grape debate once and for all. Which grape is superior—red or green—and why?",
  },
  {
    id: 'rank-cheeses',
    type: 'rank',
    emoji: '🧀',
    text: "Rank Wanda's Fave Cheeses",
    hint: 'Drag to reorder — #1 is most favourite',
    options: [
      { id: 'feta',      label: 'Feta' },
      { id: 'brie',      label: 'Brie' },
      { id: 'parmesan',  label: 'Parmesan' },
      { id: 'cheddar',   label: 'Cheddar' },
      { id: 'gruyere',   label: 'Gruyère' },
    ],
  },
  {
    id: 'scamfluencer',
    type: 'text',
    emoji: '🤑',
    text: 'If you had to become a scamfluencer, what would your scam entail?',
    hint: 'Anna Delvey is a great example!',
  },
  {
    id: 'veggie',
    type: 'choice',
    emoji: '🥦',
    text: 'Which of these veggies typically on a charcuterie board does Wanda hate?',
    options: ['Olives', 'Cucumber', 'Baby carrots', 'Cherry Tomatoes'],
  },
  {
    id: 'advice',
    type: 'text',
    emoji: '🎂',
    text: "If you're older than 30, what is one piece of advice you'd give to your younger self at 30 (or me)? If you're younger than 30, what do you hope that age will bring you?",
  },
  {
    id: 'wishes',
    type: 'text',
    emoji: '🥂',
    text: 'Wishes for Wanda—what is your wish for Wanda in this new decade?',
  },
]
