export const QUESTIONS = [
  {
    id: 'city',
    type: 'city',
    text: 'Which city/town are you in?',
  },
  {
    id: 'attendance',
    type: 'choice',
    text: 'Will you be celebrating at the soirée in NYC or joining the fun from afar?',
    options: ['In-person', 'Remote'],
  },
  {
    id: 'favourite-fruit',
    type: 'text',
    emoji: '🍊',
    text: "Before Wanda discovered and fell in love with grapefruits at the tender age of 16, what was her favourite fruit?",
    hint: 'Hint: it was NOT on the quiz last year',
  },
  {
    id: 'if-you-were-a-wine',
    type: 'wine-search',
    emoji: '🍾',
    text: 'If you were a wine, what would you be and why?',
    hint: "Think critically about this, don't just pick your fave wine because it's your fave!",
  },
  {
    id: 'rank-glasses',
    type: 'rank',
    emoji: '🍷',
    text: "Rank these from Wanda's most to least preferred vessel for drinking wine",
    hint: 'Drag to reorder — #1 is most preferred. Tap an image to enlarge it.',
    options: [
      { id: 'mug',              label: 'A Mug',                                    image: '/glasses/mug.png' },
      { id: 'angular-stem',     label: 'Angular Goblet with Tall Skinny Stem',   image: '/glasses/angular-stem.png' },
      { id: 'rounded-stem',     label: 'Rounded Goblet with Tall Skinny Stem',    image: '/glasses/rounded-stem.png' },
      { id: 'short-thick-stem', label: 'Short Wine Glass with Thick Stem',         image: '/glasses/short-thick-stem.png' },
      { id: 'stemless',         label: 'Stemless Wine Glass',                      image: '/glasses/stemless.png' },
      { id: 'wine-cooler-mug',  label: 'Wine Cooler Mug',                          image: '/glasses/wine-cooler-mug.png' },
    ],
  },
  {
    id: 'rank-wines',
    type: 'rank',
    emoji: '🍷',
    text: "Rank Wanda's fave wines",
    hint: 'Drag to reorder — #1 is most favourite',
    options: [
      { id: 'chilled-malbec',label: 'Chilled Malbec' },
      { id: 'pinot-grigio',  label: 'Pinot Grigio' },
      { id: 'pinot-noir',    label: 'Pinot Noir' },
      { id: 'riesling',      label: 'Riesling' },
      { id: 'rose',          label: 'Rosé' },
    ],
  },
  {
    id: 'grape-debate',
    type: 'choice-explain',
    emoji: '🍇',
    text: "Let's settle the great grape debate once and for all. Which grape is superior and why?",
    options: ['Green', 'Red'],
  },
  {
    id: 'rank-cheeses',
    type: 'rank',
    emoji: '🧀',
    text: "Rank Wanda's fave cheeses",
    hint: 'Drag to reorder — #1 is most favourite',
    options: [
      { id: 'brie',      label: 'Brie' },
      { id: 'cheddar',   label: 'Cheddar' },
      { id: 'feta',      label: 'Feta' },
      { id: 'gruyere',   label: 'Gruyère' },
      { id: 'parmesan',  label: 'Parmesan' },
    ],
  },
  {
    id: 'scamfluencer',
    type: 'text',
    emoji: '🤑',
    text: 'If you had to become a scamfluencer, what would your scam entail?',
    hint: 'scammers',
  },
  {
    id: 'veggie',
    type: 'choice',
    emoji: '🥦',
    text: 'Which of these veggies that are typically found on a charcuterie board does Wanda hate?',
    options: ['Baby carrots', 'Cherry tomatoes', 'Cucumbers', 'Olives'],
  },
  {
    id: 'advice',
    type: 'text',
    emoji: '🎂',
    text: "If you're older than 30, what is one piece of advice you'd give to your younger self (or Wanda) at 30?",
    subtext: "If you're younger than 30, what do you hope that age will bring you when it's your turn?",
  },
  {
    id: 'wishes',
    type: 'text',
    emoji: '✨',
    text: 'Wishes for Wanda: what is your wish for the birthday girl in her new decade?',
    hint: "Be as specific as possible please—let's only leave the universe room for magic and not misinterpretation!",
  },
]
